# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando usuário Docker
       # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
           username: ${{secrets.DOCKERHUB_USER}}
          # Password or personal access token used to log against the Docker registry
           password: ${{secrets.DOCKERHUB_PWD}}
       
      - name: Construindo a imagem e enviando para o Docker
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            gilmaroassis/kubehello:lastest
            gilmaroassis/kubehello:${{github.RUN_NUMBER}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Definindo o kubeconfig
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Efetuando o deploy no Kubernetes
        uses: Azure/k8s-deploy@v4.3
        with:
          images:
            gilmaroassis/kubehello:${{github.RUN_NUMBER}}
          manifests: |
            k8s/deployment.yaml 
